services:
  mysql:
    image: mysql:latest
    container_name: printset-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./create_database.mysql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql